[lldp] fix issue #79 - AttributeError: 'NoneType' object has no attribute 'decode' (#80)
* [lldp] fix issue #79
*  review comments - set local mgmt ip to '' if missing