[20211] Handle error seen on system where vlan interface map is not present
fixes Azure/sonic-buildimage#9996
Handle error seen on system where vlan interface map is not present.
This change requires: Azure/sonic-py-swsssdk#117
On chassis platform, on supervisor there are not ports available in config_db. So, there is no vlan interface map in counters db, which causes this error in syslog:

ERROR: MIBUpdater.start() caught an unexpected exception during update_data(). RuntimeError: Key '{COUNTERS_RIF_NAME_MAP}' unavailable in database '{COUNTERS_DB}'
- How I did it
Return empty dict if vlan interface map is not present in DB.

(cherry picked from commit 21517316df6f94fa25a2514ced7ffbf6197ae869)
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>